name: Packer

on:
  push:


jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: verify directory
        run: ls

      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          working_directory: ./packer
          target: ./app_server.json ./nginx_web_server.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          working_directory: ./packer
          arguments: "-color=false -on-error=abort"
          target: ./app_server.json ./nginx_web_server.json
